services:
  nextjs:
    build: .
    ports:
      - "3000:10000"
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - DATABASE_URL=file:/app/db/custom.db
      - PORT=10000
      - SEED_DB=true
    volumes:
      - ./db:/app/db
      - ./public:/app/public
    restart: unless-stopped
