services:
  - type: web
    name: enrique-zairtre
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: ohio  # o la región más cercana a ti
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: https://enrique-zairtre.onrender.com
      - key: DATABASE_URL
        value: file:/app/db/custom.db
      - key: NEXTAUTH_SECRET
        generateValue: true
    disk:
      name: data
      mountPath: /app/db
      sizeGB: 1